StoryTime.WebMVC/Controllers/StorySubmissionController.cs
using Microsoft.AspNet.Identity;
using StoryTime.Models;
using StoryTime.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoryTime.WebMVC.Controllers
{
    [Authorize]
    //Authorize student role permission
    public class StorySubmissionController : Controller
    {
        [Authorize(Roles ="Admin")]
        public ActionResult AdminIndex()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new StorySubmissionService(userId);
            var model = service.GetStudentNameFromId(service.AdminGetAllStorySubmissions());
            return View(model);
        }

        // GET: GeneratedPrompt
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new StorySubmissionService(userId);
            var model = service.GetStudentNameFromId(service.GetStorySubmissions());
            return View(model);
        }

        public ActionResult Create()
        {
            var service = CreateStorySubmissionService();
            var model = service.PromptResult();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StorySubmissionCreate model)
        {
            {
                if (!ModelState.IsValid) return View(model);

                var service = CreateStorySubmissionService();

                if (service.CreateStorySubmission(model))
                {
                    TempData["SaveResult"] = "Your story has been submitted.";
                    return RedirectToAction("Index");
                };

                ModelState.AddModelError("", "Your story could not be submitted.");
                return View(model);
            }
        }

        public ActionResult Details(int id)
        {
            if(User.IsInRole("Admin"))
            {
                var service = CreateStorySubmissionService();
                var model = service.AdminGetStoryById(id);

                model.StudentName = service.GetStudentName(model.StudentId.ToString());
                return View(model);
            }
            if(User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                var service = CreateStorySubmissionService();
                var model = service.GetStoryById(id);
                return View(model);
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            if (User.IsInRole("Admin"))
            {
                var service = CreateStorySubmissionService();
                var detail = service.AdminGetStoryById(id);
                var model =
                    new StorySubmissionEdit
                    {
                        StoryId = detail.StoryId,
                        StoryTitle = detail.StoryTitle,
                        StoryText = detail.StoryText
                    };
                return View(model);
            }

            if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                var service = CreateStorySubmissionService();
                var detail = service.GetStoryById(id);
                var model =
                    new StorySubmissionEdit
                    {
                        StoryId = detail.StoryId,
                        StoryTitle = detail.StoryTitle,
                        StoryText = detail.StoryText
                    };
                return View(model);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, StorySubmissionEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.StoryId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateStorySubmissionService();

            if (User.IsInRole("Admin"))
            {
                if (service.AdminUpdateStorySubmission(model))
                {
                    TempData["SaveResult"] = "Your comments have been recorded.";
                    return RedirectToAction("AdminIndex");
                }
            }

            if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
            {
                if (service.UpdateStorySubmission(model))
                {
                    TempData["SaveResult"] = "Your story was updated for the teacher's review.";
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Your story could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = CreateStorySubmissionService();
            var model = service.AdminGetStoryById(id);
            model.StudentName = service.GetStudentName(model.StudentId.ToString());
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateStorySubmissionService();
            service.DeleteStorySubmission(id);
            TempData["SaveResult"] = "Your character was deleted.";
            return RedirectToAction("AdminIndex");
        }

        private StorySubmissionService CreateStorySubmissionService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new StorySubmissionService(userId);
            return service;
        }
    }
}

StoryTime.WebMVC/Views/StorySubmission/AdminIndex.cshtml
@model IEnumerable<StoryTime.Models.StorySubmissionListItem>

@{
    ViewBag.Title = "AdminIndex";
}

<center><h2 class="font">Submitted Assignments</h2></center>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

<div class="index">
    <p class="font">
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr class="font">
            <th>
                @Html.DisplayNameFor(model => model.StoryId)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.StudentId)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.StudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StoryTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedUtc)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StoryId)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.StudentId)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.StudentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StoryTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedUtc)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.StoryId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.StoryId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.StoryId })
                </td>
            </tr>

        }
    </table>
</div>

StoryTime.WebMVC/Views/StorySubmission/Create.cshtml
@model StoryTime.Models.StorySubmissionCreate

@{
    ViewBag.Title = "Create";
}

<center><h2 class="font">Write me a story!</h2></center>

<div class="create">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div>
                <ul class="prompt">
                    <li><b class="font">@Model.Character</b> finds themselves in...</li>
                    <li><b class="font">@Model.Location</b> where...</li>
                    <li><b class="font">@Model.Twist</b></li>
                </ul>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(model => model.StoryTitle, htmlAttributes: new { @class = "control-label col-md-2 font" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoryTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoryTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StoryText, htmlAttributes: new { @class = "control-label col-md-2 font" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoryText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoryText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default font" />
                </div>
            </div>

        </div>

    }

    <div>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "AdminIndex")

        }
        @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "Index")

        }
    </div>
    </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

StoryTime.WebMVC/Views/StorySubmission/Delete.cshtml
@model StoryTime.Models.StorySubmissionDetail

@{
    ViewBag.Title = "Delete";
}

<center class="font">
    <h2>Delete Story</h2>
    <h3>Are you sure you want to delete this story?</h3>
</center>
<div class="index">
    <dl class="dl-horizontal">
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryId)
        </dd>
        <br />
        @*<dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>*@

        <dt class="font">
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryTitle)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryText)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt class="font">
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default font" /> |
            @Html.ActionLink("Back to List", "AdminIndex", "StorySubmission")
        </div>
    }
</div>

StoryTime.WebMVC/Views/StorySubmission/Details.cshtml
@model StoryTime.Models.StorySubmissionDetail

@{
    ViewBag.Title = "Details";
}

<center><h2 class="font">Story Details</h2></center>

<div class="index">
    <dl class="dl-horizontal">
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryId)
        </dd>
        <br />
        @*<dt>
                @Html.DisplayNameFor(model => model.StudentId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StudentId)
            </dd>*@

        <dt class="font">
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryTitle)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.StoryText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoryText)
        </dd>
        <br />
        <dt class="font">
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt class="font">
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.StoryId }) |
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "AdminIndex")
        }
        @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "Index")
        }
    </p>
</div>

StoryTime.WebMVC/Views/StorySubmission/Edit.cshtml
@model StoryTime.Models.StorySubmissionEdit

@{
    ViewBag.Title = "Edit";
}

<center><h2 class="font">Edit Story</h2></center>

<div class="index">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.StoryId)

            <div class="form-group">
                @Html.LabelFor(model => model.StoryTitle, htmlAttributes: new { @class = "control-label col-md-2 font" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoryTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoryTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StoryText, htmlAttributes: new { @class = "control-label col-md-2 font" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoryText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoryText, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default edit-btn font" />
                </div>
            </div>
        </div>
    }

    <div>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "AdminIndex")
        }
        @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
        {
            @Html.ActionLink("Back to List", "Index")
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoryTime.WebMVC/Views/StorySubmission/Index.cshtml
@model IEnumerable<StoryTime.Models.StorySubmissionListItem>
<head>
    @{
        ViewBag.Title = "Index";
    }

    @Scripts.Render("~/Content/Site.css")
</head>

<center><h2 class="font">My Stories</h2></center>

@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}

    <div class="index">
        <p class="font">
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr class="font">
                <th>
                    @Html.DisplayNameFor(model => model.StoryId)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.StudentId)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.StudentName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StoryTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedUtc)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoryId)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.StudentId)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoryTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedUtc)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.StoryId }, new { style = "color:#DCA258" }) |
                        @Html.ActionLink("Details", "Details", new { id = item.StoryId }, new { style = "color:#DCA258" }) @*|*@
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.StoryId })*@
                    </td>
                </tr>
            }

        </table>
    </div>